### ISSUE TITLE
Validation for DataDog alias metadata

### ISSUE THREAD

**Issue by tancnle** [grosser/kennel#76]
I came across this use case when running `kennel:plan` on one of my project.

Symbol validation for Optional fails on DataDog alias metadata
```ruby
metadata: {    
  "autosmooth(avg:some_metric)" => {
    alias: "With Labels"
  }
}
```

The related validation logic can be found here
https://github.com/grosser/kennel/blob/8463991be3838ca767c99998583ba8b52e9e2f86/lib/kennel/optional_validations.rb#L20

Few thoughts
1. Downgrade this validation to warning and still proceed with running `kennel:plan`
2. Exclude this rule for metadata

**Comment by grosser** [comment]
what is the error message you saw ?

**Comment by grosser** [comment]
option 2 makes the most sense ... if you can make a PR to ignore this variant that would be 🥇

**Comment by tancnle** [comment]
This is the validation error message

```log
rake aborted!
Kennel::Models::Base::ValidationError: crystal_ball_answer_bot_timeboard:crystal-ball-answer-bot only use Symbols to avoid permanent diffs ("autosmooth(avg:zendesk.crystal_ball_k8.automaticanswers.database.fetch_embeds.95percentile{$env,labels:true})", "autosmooth(avg:zendesk.crystal_ball_k8.automaticanswers.database.fetch_embeds.95percentile{$env,labels:false})", "avg:zendesk.crystal_ball_k8.automaticanswers.database.fetch_embeds.count{$env,$pod,labels:true}.as_count()", "avg:zendesk.crystal_ball_k8.automaticanswers.database.fetch_embeds.count{$env,$pod,labels:false}.as_count()", "autosmooth(avg:aws.rds.cpuutilization{$env,name:answer-bot-embeddings-aurora-dbdb,region:us-east-1})", "autosmooth(avg:aws.rds.cpuutilization{$env,name:answer-bot-embeddings-aurora-dbdb,region:eu-central-1})")
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel/models/base.rb:144:in `invalid!'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel/optional_validations.rb:23:in `validate_json'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel/models/dash.rb:75:in `validate_json'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel/models/dash.rb:45:in `as_json'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel.rb:41:in `block in generate'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel.rb:38:in `each'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel.rb:38:in `generate'
/Users/tle/.gem/ruby/2.5.1/gems/kennel-1.32.0/lib/kennel/tasks.rb:17:in `block (2 levels) in <top (required)>'
/Users/tle/.gem/ruby/2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/tle/.gem/ruby/2.5.1/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/Users/tle/.gem/ruby/2.5.1/bin/bundle:23:in `load'
/Users/tle/.gem/ruby/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => kennel:plan => kennel:generate
(See full trace by running task with --trace)
```
